### ISSUE TITLE
PMIDs are not recognized

### ISSUE THREAD

**Issue by lbreuza** [ebi-uniprot/Protein2GO#6] opened 2015-10-09 09:07 UTC
Hi,
I get this message for all the PMIds I submit:

WARNING: This identifier is not recognised by Protein2GO; it can, however, still be annotated if you are confident that it is valid.

What am I supposed to do?
Thanks.
Lionel

**Comment by tonysawfordebi** [comment] 2015-10-09 09:12
This is only a warning message, so you can ignore it and annotate the paper as normal.

The problem is caused by a change to the way that EuropePMC's web services work that has broken the PMID lookup functionality in P2G. I have contacted them about this, and will restore things to normal ASAP.

Tony

**Comment by tonysawfordebi** [comment] 2015-10-09 12:46
Issue now fixed; there was a bug in the EPMC code.

**Closed by tonysawfordebi** 2015-10-09 12:46 UTC
